#!/bin/sh
# -*- sh -*-

statsfile=${statsfile:-/var/lib/munin/plugin-state/TP-Link_TD-W9970-munin-output.txt}

: << =cut

=head1 NAME

Line Stats - Plugin to get TP-Link TD-W9970 line stats

=head1 NOTES

Fetches line attenuation

=head1 AUTHOR

Adam Smith
Modified for TP-Link TD-W9970 by Phoenix09

=head1 LICENSE

GPLv3

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

if [ "$1" = "config" ]; then
	echo "graph_title Line Attenuation (dB)"
	echo 'graph_args --base 1000'
	echo 'graph_vlabel Line Attenuation (dB)'
	echo 'graph_category TD-W9970'
	echo 'graph_scale no'
	echo "up.label Upstream"
	echo "down.label Downstream"
	exit 0
fi

echo -n "down.value "
awk -F = '/downstreamAttenuation=/ {print $2/10}' $statsfile

echo -n "up.value "
awk -F = '/upstreamAttenuation=/ {print $2/10}' $statsfile

exit 0
