#!/bin/sh
# -*- sh -*-

statsfile=${statsfile:-/var/lib/munin/plugin-state/TP-Link_TD-W9970-munin-output.txt}

: << =cut

=head1 NAME

Line Stats - Plugin to get TP-Link TD-W9970 line stats

=head1 NOTES

Fetches attainable sync speed vs actual sync speed

=head1 AUTHOR

Adam Smith
Modified for TP-Link TD-W9970 by Phoenix09

=head1 LICENSE

GPLv3

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

if [ "$1" = "config" ]; then
	echo "graph_title Maximum Attainable Speed"
	echo 'graph_args --base 1000'
	echo 'graph_vlabel Max Speed (bps)'
	echo 'graph_category TD-W9970'
	echo 'graph_scale yes'
	echo 'graph_order downstream upstream'
	echo 'downstream.label Downstream'
	echo 'downstream.draw AREA'
	echo 'upstream.label Upstream'
	echo 'upstream.draw AREA'
	exit 0
fi

echo -n "downstream.value "
awk -F = '/downstreamMaxRate=/ {print $2*1000}' $statsfile

echo -n "upstream.value "
awk -F = '/upstreamMaxRate=/ {print $2*1000}' $statsfile

exit 0
