#!/bin/sh
# -*- sh -*-

statsfile=${statsfile:-/var/lib/munin/plugin-state/TP-Link_TD-W9970-munin-output.txt}

: << =cut

=head1 NAME

Line Stats - Plugin to get TP-Link TD-W9970 line stats

=head1 NOTES

Fetches link uptime

=head1 AUTHOR

Adam Smith
Modified for TP-Link TD-W9970 by Phoenix09

=head1 LICENSE

GPLv3

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

if [ "$1" = "config" ]; then
	echo "graph_title ptm1 Uptime in days"
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel VDSL Uptime in days'
	echo 'graph_category TD-W9970'
	echo 'graph_scale no'
	echo 'uptime.label Uptime in days'
	echo 'uptime.draw AREA'
	exit 0
fi

echo -n "uptime.value "
awk -F = '/totalStart=/ {print $2/86400}' $statsfile

exit 0
